language: node_js
sudo: false
node_js:
  - v5
  - v4
  - '0.12'

cache:
   directories:
     - node_modules
     - bower_components

after_success:
  - cat ./coverage/mocha/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
